### PSQL connection with springboot

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/joblist
    username: BK # or lowercase if Postgres created lowercase role
    password: bkpass
  jpa:
    hibernate:
      ddl-auto: update ### creates table automatically
    show-sql: true
